
function Tyc() {
  return (
    <main>
        <div className="tyc-container">
            <h3 className="tyc-h3">Términos y Condiciones:</h3>
            <p className="tyc-p">Esta página web es propiedad y está operada por María Begué Moratalla. Estos Términos establecen los términos y condiciones bajo los cuales puedes usar esta página web y los servicios ofrecidos en la misma. Esta página web ofrece a los visitantes contenido y herramientas educativas sobre desarrollo personal y liderazgo. Al acceder o usar esta página web, o adquirir sus productos o servicios, usted aprueba que ha leído, entendido y aceptado estar sujeto a estos Términos:</p>
            <p className="tyc-p">Para usar esta página web y/o adquirir sus servicios, debes tener al menos 18 años de edad, o la mayoría de edad legal en tu jurisdicción, y poseer la autoridad legal, el derecho y la libertad para participar en estos Términos como un acuerdo vinculante. No tienes permitido utilizar esta página web y/o adquirir sus servicios o productos si hacerlo está prohibido en tu país o en virtud de cualquier ley o regulación aplicable a tu caso.</p>
            <p className="tyc-p">Al comprar un artículo, aceptas que: (i) eres responsable de leer el listado completo de características del artículo antes de comprometerte a comprarlo: (ii) celebras un contrato legalmente vinculante para comprar un artículo cuando te comprometes a comprar un artículo y completas el proceso de check-out en la página de pago.</p>
            <p className="tyc-p">Los precios que cobramos por usar nuestros servicios o productos se enumeran en la página web. Nos reservamos el derecho de cambiar nuestros precios para los productos o servicios que se muestran en cualquier momento y de corregir los errores de precios que pueden ocurrir inadvertidamente. Toda la información adicional sobre precios e impuestos sobre las ventas está disponible en la página de pagos. </p>
            <p className="tyc-p">Podemos, sin aviso previo, cambiar los servicios o productos; dejar de proporcionar los servicios o productos, o cualquier característica de los servicios o productos que ofrecemos; o crear límites para los servicios o productos. Podemos  suspender de manera permanente o temporal el acceso a los servicios sin previo aviso ni responsabilidad por cualquier motivo, o sin ningún motivo.</p>
            <p className="tyc-p">Los servicios y productos, y todos los materiales incluidos o transferidos, incluyendo, sin limitación, software, imágenes, texto, gráficos, logotipos, patentes, marcas registradas, marcas de servicio, derechos de autor, fotografías, audio, videos, música y todos los Derechos de Propiedad Intelectual relacionados con ellos, son la propiedad exclusiva de María Begué Moratalla. Salvo que se indique explícitamente en este documento, no se considerará que nada en estos Términos crea una licencia en o bajo ninguno de dichos Derechos de Propiedad Intelectual, y tú aceptas no vender, licenciar, alquilar, modificar, distribuir, copiar, reproducir, transmitir, exhibir públicamente, realizar públicamente, publicar, adaptar, editar o crear trabajos derivados de los mismos.</p>
            <p className="tyc-p">Podemos terminar o suspender de manera permanente o temporal tu acceso al servicio sin previo aviso y responsabilidad por cualquier razón, incluso si a nuestra sola determinación tu violas alguna disposición de estos Términos o cualquier ley o regulación aplicable. Puedes descontinuar el uso y solicitar cancelar tu cuenta y / o cualquier servicio en cualquier momento. </p>
            <p className="tyc-p">Usted acuerda indemnizar y eximir de responsabilidad a María Begué Moratalla de cualquier demanda, pérdida, responsabilidad, reclamación o gasto (incluidos los honorarios de abogados) que terceros realicen en tu contra como consecuencia de, o derivado de, o en relación con tu uso de la página web o cualquiera de los servicios o productos ofrecidos en la página web.</p>
            <p className="tyc-p">En la máxima medida permitida por la ley aplicable, en ningún caso María Begué Moratalla será responsable por daños indirectos, punitivos, incidentales, especiales, consecuentes o ejemplares, incluidos, entre otros, daños por pérdida de beneficios, buena voluntad, uso, datos u otras pérdidas intangibles, que surjan de o estén relacionadas con el uso o la imposibilidad de utilizar el servicio o los productos. </p>
            <p className="tyc-p">Nos reservamos el derecho de modificar estos términos a nuestra entera discreción. Por lo tanto, debes revisar estas páginas periódicamente. Cuando cambiemos los Términos de una manera material, te notificaremos que se han realizado cambios importantes en los Términos. El uso continuado de la página web o nuestro servicio después de dicho cambio constituye tu aceptación de los nuevos Términos. Si no aceptas alguno de estos términos o cualquier versión futura de los Términos, no uses o  accedas (o continúes accediendo) a la página web o a los servicios o productos.</p>
            <p className="tyc-p">Aceptas recibir de vez en cuando nuestros mensajes y materiales de promoción, por correo postal, correo electrónico o cualquier otro formulario de contacto que nos proporciones (incluido tu número de teléfono para llamadas o mensajes de texto). Si no deseas recibir dichos materiales o avisos de promociones, simplemente avísanos en cualquier momento.</p>
            <p className="tyc-p">Estos Términos, los derechos y recursos provistos aquí, y todos y cada uno de los reclamos y disputas relacionados con este y/o los servicios o productos, se regirán, interpretarán y aplicarán en todos los aspectos única y exclusivamente de conformidad con las leyes sustantivas internas de España, concretamente de la Comunidad Valenciana, sin respeto a sus principios de conflicto de leyes. Todos los reclamos y disputas se presentarán y usted acepta que sean decididos exclusivamente por un tribunal de jurisdicción competente ubicado en Valencia. La aplicación de la Convención de Contratos de las Naciones Unidas para la Venta Internacional de Bienes queda expresamente excluida.</p>

            <h3 className="tyc-h3">Política de privacidad:</h3>
            <p className="tyc-p">Recibimos, recopilamos y almacenamos cualquier información que ingrese en nuestro sitio web o nos proporciones de otra manera. Además, recogemos la dirección de protocolo de Internet (IP) utilizada para conectar tu computadora a Internet; datos de inicio de sesión, dirección de correo electrónico, contraseña, información de la computadora y la conexión y el historial de compras. Podemos usar herramientas de software para medir y recopilar información de la sesión, incluidos los tiempos de respuesta de la página, la duración de las visitas a determinadas páginas, la información de interacción de la página y los métodos utilizados para navegar fuera de la página. También recopilamos información de identificación personal (incluido nombres, correo electrónico, contraseña, comunicaciones), detalles de pago (incluida la información de la tarjeta de crédito o débito), comentarios, sugerencias, reseñas de productos, recomendaciones y perfil personal.</p>
            <p className="tyc-p">Cuando realizas una transacción en nuestra página web, como parte del proceso, recopilamos información personal que nos proporcionas, como tu nombre, dirección física y dirección de correo electrónico. Tu información personal será utilizada solo para los motivos específicos indicados anteriormente.</p>
            <p className="tyc-p">Recopilamos dicha información personal y no personal para los siguientes propósitos: </p>
            <p className="tyc-p">Para proporcionar y operar los servicios y/o productos; </p>
            <p className="tyc-p">Para proporcionar a nuestros usuarios asistencia continua al cliente y soporte técnico; </p>
            <p className="tyc-p">Para poder contactar a nuestros visitantes y usuarios con avisos generales y personalizados relacionados con el servicio y/o producto y mensajes promocionales; </p>
            <p className="tyc-p">Para crear datos estadísticos agregados y otra información no personal agregada o deducida, que nosotros o nuestros socios comerciales podamos utilizar para proporcionar y mejorar nuestros servicios respectivos;</p>
            <p className="tyc-p">Para cumplir con las leyes y regulaciones aplicables</p>
            <p className="tyc-p">Nuestra página web está alojada en la plataforma Wix.com. Wix.com nos proporciona la plataforma en línea que nos permite venderte nuestros productos y servicios. Tus datos pueden almacenarse a través del almacenamiento de datos de Wix.com, las bases de datos y las aplicaciones generales de Wix.com. Ellos almacenan tus datos en servidores seguros detrás de un firewall.</p>
            <p className="tyc-p">Todas las pasarelas de pago directo ofrecidas por Wix.com y utilizadas por nuestra compañía se adhieren a los estándares establecidos por PCI-DSS administrados por el PCI Security Standards Council, que es un esfuerzo conjunto de marcas como Visa, MasterCard, American Express y Discover. Los requisitos de PCI-DSS ayudan a garantizar el manejo seguro de la información de la tarjeta de crédito por parte de nuestra tienda y sus proveedores de servicios.</p>
            <p className="tyc-p">Podemos comunicarnos contigo para notificarte sobre tu cuenta, para solucionar problemas con tu cuenta, resolver una disputa, cobrar tarifas o dinero adeudado, para sondear tus opiniones a través de encuestas o cuestionarios, para enviar actualizaciones sobre nuestra empresa, productos o servicios, o cuando sea necesario para contactarte para hacer cumplir nuestro Acuerdo de usuario, las leyes nacionales aplicables y cualquier acuerdo que podamos tener contigo. A estos efectos, podemos comunicarnos contigo por correo electrónico, teléfono, mensajes de texto y correo postal.</p>
            <p className="tyc-p">Si no deseas que procesemos tus datos, contáctanos a mariabegue2@gmail.com o envíanos un correo a C/Cofrentes n3 pta 7 - 46010, Valencia - España.</p>
            <p className="tyc-p">Nos reservamos el derecho de modificar esta política de privacidad en cualquier momento, por lo tanto, revísala con frecuencia. Los cambios y aclaraciones tendrán efecto inmediatamente después de su publicación en la página web. Si realizamos cambios sustanciales a esta política, te notificaremos que se ha actualizado, para que sepas qué información recopilamos, cómo la usamos y en qué circunstancias, si corresponde, usamos o divulgamos la información.</p>
            <p className="tyc-p">Si deseas: acceder, corregir, modificar o eliminar cualquier información personal que tengamos sobre ti, estás invitado a contactarnos en mariabegue2@gmail.com o envíanos un correo a C/Cofrentes n3 pta 7 - 46010, Valencia - España.</p>
        </div>
    </main>
  );
};

export default Tyc;